### 2D array

In [2]:
import numpy as np

In [3]:
a=np.array([[2,3,7],[8,67,4],[15,48,93],[56,3,38]])
a

array([[ 2,  3,  7],
       [ 8, 67,  4],
       [15, 48, 93],
       [56,  3, 38]])

### Index of [Row][Column]

In [5]:
a[2][2]

93

### Index(R,C)

In [6]:
a[3,:]

array([56,  3, 38])

In [7]:
a[:,(1,2)]

array([[ 3,  7],
       [67,  4],
       [48, 93],
       [ 3, 38]])

In [9]:
a[(3,1),:]

array([[56,  3, 38],
       [ 8, 67,  4]])

### Statisctical parameters

In [10]:
np.exp(a)

array([[7.38905610e+00, 2.00855369e+01, 1.09663316e+03],
       [2.98095799e+03, 1.25236317e+29, 5.45981500e+01],
       [3.26901737e+06, 7.01673591e+20, 2.45124554e+40],
       [2.09165950e+24, 2.00855369e+01, 3.18559318e+16]])

In [11]:
np.sqrt(a)

array([[1.41421356, 1.73205081, 2.64575131],
       [2.82842712, 8.18535277, 2.        ],
       [3.87298335, 6.92820323, 9.64365076],
       [7.48331477, 1.73205081, 6.164414  ]])

In [22]:
b=np.log(a)
b

array([[0.69314718, 1.09861229, 1.94591015],
       [2.07944154, 4.20469262, 1.38629436],
       [2.7080502 , 3.87120101, 4.53259949],
       [4.02535169, 1.09861229, 3.63758616]])

In [13]:
np.max(a)

93

In [14]:
np.min(a)

2

In [15]:
np.argmax(a)

8

In [16]:
np.argmin(a)

0

In [17]:
np.square(a)

array([[   4,    9,   49],
       [  64, 4489,   16],
       [ 225, 2304, 8649],
       [3136,    9, 1444]], dtype=int32)

In [18]:
np.std(a)

29.63200221982233

In [19]:
np.var(a)

878.0555555555555

In [20]:
np.mean(a)

28.666666666666668

In [23]:
np.round(b,decimals=3)

array([[0.693, 1.099, 1.946],
       [2.079, 4.205, 1.386],
       [2.708, 3.871, 4.533],
       [4.025, 1.099, 3.638]])

In [24]:
c=a+b
c

array([[ 2.69314718,  4.09861229,  8.94591015],
       [10.07944154, 71.20469262,  5.38629436],
       [17.7080502 , 51.87120101, 97.53259949],
       [60.02535169,  4.09861229, 41.63758616]])

In [27]:
s=np.array(["fball","football","cricket","fball","baseball","volleyball"])
np.unique(s)

array(['baseball', 'cricket', 'fball', 'football', 'volleyball'],
      dtype='<U10')