## NUMPY : Numerical Python

In [1]:
import numpy as np

### BASICS of array

In [3]:
np.array([2,8,4,3])


array([2, 8, 4, 3])

In [2]:
np.array([3, 5.5, 1, "ANU", 4, 9])

array(['3', '5.5', '1', 'ANU', '4', '9'], dtype='<U32')

In [5]:
arr = np.array([3,6,9,5])
arr

array([3, 6, 9, 5])

In [8]:
list_inside_arr = [[1,1,1],[2,2,2],[3,3,3]]
np.array(list_inside_arr)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [9]:
a=np.array((2,3,4))
a

array([2, 3, 4])

In [11]:
np.array({a:2,b:4,c:6})

TypeError: unhashable type: 'numpy.ndarray'

In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,89,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86])

### Zeros

In [15]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((3,2),int)

array([[0, 0],
       [0, 0],
       [0, 0]])

### Ones

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones(30,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [22]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Shitf + tab = Descripction of each commands

In [25]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [26]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.linspace(50,70,8)

array([50.        , 52.85714286, 55.71428571, 58.57142857, 61.42857143,
       64.28571429, 67.14285714, 70.        ])

In [30]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Random

### np.random.rand(no.of rows, no.of columns)

In [34]:
np.random.rand(5,4)

array([[0.498812  , 0.11665447, 0.69907637, 0.12898372],
       [0.02961227, 0.49523691, 0.02734062, 0.94926354],
       [0.04357935, 0.32228358, 0.53546788, 0.55888443],
       [0.3662801 , 0.49132632, 0.1948921 , 0.03549423],
       [0.77021009, 0.9957961 , 0.79621418, 0.33243215]])

In [35]:
np.random.randn(5,4)

array([[-0.89582702, -0.63982245,  1.45949499, -0.90267057],
       [-1.06989321, -0.38469203, -0.34196513, -0.3656059 ],
       [ 1.1984793 ,  1.70725903,  1.99493768,  0.13132413],
       [ 1.89525538, -0.06994559, -0.27191758, -0.15503863],
       [-1.11333253, -1.48832897, -2.35168789, -0.25689625]])

In [36]:
np.random.randint(5,4)

ValueError: low >= high

In [37]:
np.random.randint(67,89)

79

In [38]:
np.random.randint(67,89,50)

array([79, 69, 68, 78, 87, 85, 76, 81, 86, 87, 88, 74, 72, 83, 68, 82, 85,
       73, 84, 82, 72, 73, 79, 83, 88, 80, 78, 82, 72, 81, 74, 79, 72, 83,
       80, 69, 75, 81, 82, 71, 84, 83, 73, 82, 75, 69, 78, 75, 79, 76])

In [40]:
a=np.arange(50)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [41]:
b=np.random.randint(0,100,20)
b

array([87, 55, 87,  0, 87, 20, 59, 92, 11, 49, 97,  0, 13, 47, 39,  9, 42,
        7,  6, 92])

In [42]:
b=np.random.randint(50,70,5)
b

array([68, 63, 58, 55, 52])

### RESHAPE

In [43]:
a.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [46]:
a.reshape(7,6)

ValueError: cannot reshape array of size 50 into shape (7,6)

In [45]:
a.reshape(5,4)

ValueError: cannot reshape array of size 50 into shape (5,4)

In [60]:
a.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### MIN MAX argmin argmax

In [86]:
b.min()

52

In [49]:
a.min()

0

In [50]:
b.argmin()

4

In [51]:
b.max()

68

In [52]:
b.argmax()

0

In [53]:
b

array([68, 63, 58, 55, 52])

In [54]:
b.dtype

dtype('int32')

In [55]:
b

array([68, 63, 58, 55, 52])

In [66]:
d=np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
d.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [69]:
d.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Slicing

In [82]:
a = np.arange(40,60)
a

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59])

In [72]:
a[6:10]

array([46, 47, 48, 49])

In [74]:
a[1:4]=100
a

array([ 40, 100, 100, 100,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59])

In [83]:
a[0:10]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [85]:
a[0:10]=5000
a

array([5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000,   50,
         51,   52,   53,   54,   55,   56,   57,   58,   59])

In [76]:
a[:]

array([ 40, 100, 100, 100,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59])

In [79]:
a[:] =70
a

array([70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70,
       70, 70, 70])